apiVersion: v1
kind: ConfigMap
metadata:
  name: mediator-config
data:
  AGENT_LABEL: {{ .Values.mediator.config.AGENT_LABEL | quote }}
  WALLET_NAME: {{ .Values.mediator.config.WALLET_NAME | quote }}
  ADDRESS: {{ .Values.mediator.config.ADDRESS | quote }}
  PORT: {{ .Values.mediator.config.PORT | quote }}
  SERVICE_ACCOUNT: {{ .Values.mediator.secrets.SERVICE_ACCOUNT | quote }}
  POSTGRES_HOST: {{ .Values.rds.host | quote }} 
  #POSTGRES_PORT: {{ .Values.rds.port | quote }} 
  #POSTGRES_DB: {{ .Values.rds.databases.mediatordb | quote }} 

