apiVersion: v1
kind: Secret
metadata:
  name: mediator-secrets
type: Opaque
data:
  POSTGRES_USER: {{ .Values.rds.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.rds.password | quote }}
  WALLET_KEY: {{ .Values.mediator.secrets.WALLET_KEY | quote }}